### ISSUE TITLE
Results differ slightly from PMCMR

### ISSUE THREAD

**Issue by dyballa** [maximtrp/posthocs#2]
First off, congrats on the great idea of porting this to Python.
I just ran it on R's InsectSprays data (with no p_adjust method) and I'm getting slightly different p-values than those from PMCMR for a couple of the group comparisons (B & C and F & C). Do you know why that might be?
Thanks!

**Comment by maximtrp** [comment]
@dyballa 
Thanks for giving it a try. What test are you using?

**Comment by dyballa** [comment]
@maximtrp With PMCMR, I'm using posthoc.kruskal.conover.test with p.adjust.method="none".

**Comment by maximtrp** [comment]
@dyballa I've compared the original PMCMR algorithm for Conover's test and my port of it line by line. This is not related to _posthocs_ package. The differences arise on calculating p values, using SciPy's `scipy.stats.t.cdf()` function. Anyway, differences are seen only in _extremely_ small values. Probably, it is related to rounding error. Needs further investigation.

**Comment by dyballa** [comment]
@maximtrp Interesting! Thanks, I appreciate your checking this.

**Comment by josef-pkt** [comment]
@maximtrp   It is numerically better to use scipy distribution `sf` for upper tail pvalues
in cases like this, cdf should be replaced by sf
`p_value = 2. * (1. - ss.t.cdf(np.abs(t_value), df = x_len_overall - x_len))`
to
`p_value = 2. * (ss.t.sf(np.abs(t_value), df = x_len_overall - x_len))`

1 - cdf is limited in values to floating point precision at 1, while sf in most distribution can compute much smaller tail probabilities.

**Comment by maximtrp** [comment]
@josef-pkt Thank you!
